apiVersion: apps/v1
kind: Deployment
metadata:
  name: lol-serving-deployment
  namespace: ${namespace}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lol-serving
  template:
    metadata:
      labels:
        app: lol-serving
    spec:
      containers:
      - name: lol-serving
        image: lol-model:3.10.6
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 64M
            cpu: 10m
          limits:
            memory: 128M
            cpu: 20m
